---
- name: Stop SSSD service to test AD integration playbook
  hosts: "{{ host_list }}"
  become: true

  tasks:
    - name: Stop SSSD service
      service:
        name: sssd
        state: stopped
        enabled: false
...
